:PROPERTIES:
:ID:       97681afe-9bed-4e69-b989-211b43222d75
:END:
#+title: 2021-05-06
* 《海边的卡夫卡》半程阅读笔记

这个故事仿佛无甚新意。主角被父亲预言说“总有一天你将要杀死自己的父亲，并与母亲和姐姐
交合”。这不就是《俄狄浦斯王》中的情节吗？就连小说中大岛也一再提起这是《俄狄浦斯王》中的预言。
所以接下来要看的是，田村卡夫卡会如预言所说，杀父并与母亲姐姐交合吗？

这本在iPad 12.9英寸的微信读书里大概520页的书，被我读到了280也，已过半程。

首先，这个故事迄今为止都在双线叙事：一边是离家出走的14岁少年，田村卡夫卡，离开东京
来到高松，遇到一个名为樱花的女孩，在她家过夜，被她用手解决性需求，然后在图书馆管
理员大岛的帮助下，进入图书馆安住、工作，爱上15岁的佐伯；另一边是经历了二战的老人
中田，二战时从东京疏散到乡下上课，经历了学生集体昏迷事件，从此脑袋不好使了，不认识
字，忘掉了以前的事，离开学校后以木匠手艺为生，木工公司倒闭后领知事大人的救济加上
帮人找猫为生，无欲无求，日子过得过去。但帮忙找小三毛猫时遇上了杀猫怪人琼尼 沃克，
不得已杀死了他，然后自己身上起了变化，费劲力气，在许多人帮助下离开东京，彷佛有人
指引一般往西行，隐约好像要与田村卡夫卡会合。

樱花看来是他的姐姐。

杀父看来已经实现了。中田杀死了琼尼 沃克，报纸上却说是田村卡夫卡的父亲被杀。在案发
当天田村卡夫卡莫名其妙躺倒在野地里，T恤上沾血。而中田杀人时身体也仿佛起了什么变化。

他也爱上了15岁的佐伯，甚至为此嫉妒佐伯的二十岁在大学运动中无谓死去的青梅竹马，他
平生第一次地嫉妒一个人。同时他也猜想佐伯是否就是在四岁时带着姐姐离开爸爸和自己的妈妈。

我觉得我有些厌倦村上春树了。他故事里的男人都真诚，坚毅，受女人喜欢。

聪明如我的读者已经猜到了故事最令人震惊的地方。那么还有什么可以值得继续书写呢？村上？
村上是要写命运不可违抗的希腊戏剧的现代版，写卡夫卡如何同母亲交合吗？对了，还有
中田呢。中田会纠正（阻止）卡夫卡吗？

他太爱自己的主角了，不忍心他们受苦。

看完这本书后去看《被掩埋的巨人》和《克拉拉与太阳》，英文版。石黑一雄。虽然也属于
日本人，但人家在英国长大，用英语写作，应该不会是惯常的日语文学味道。
