[package]
name = "cookbook"
version = "0.1.0"
authors = ["VitalyR <vitalyankh@gmail.com>"]
edition = "2018"

[dependencies]
tar="*"
ansi_term="*"
flate2="*"
wallpaper = "2.0.1"
orbtk = { git = "https://gitlab.redox-os.org/redox-os/orbtk.git" }
cursive = "0.11.1"
lazy_static = "1.3.0"
rand = "0.6.5"
termion = {git ="https://gitlab.redox-os.org/redox-os/termion"}
extra={git="https://gitlab.redox-os.org/redox-os/libextra"}
