[package]
authors = ["VitalyR <vitalyankh@gmail.com>"]
edition = "2021"
name = "rustua"
version = "0.1.0"
[dependencies]
serde = "*"
serde_json = "*"

[dependencies.bevy]
features = ["wayland"]
version = "0.5"
