# build command:
# 1. use g++:
#    cmake -G Ninja -S . -B build -DCMAKE_CXX_COMPILER=/usr/bin/g++
#    cmake --build build
# cmake --build build  0.08s user 0.03s system 97% cpu 0.111 total
# 2. use clang++:
#    cmake -G Ninja -S . -B build -DCMAKE_CXX_COMPILER=/usr/local/bin/clang++
#    cmake --build build
# cmake --build build  0.04s user 0.03s system 95% cpu 0.079 tota

build_clang:
   #/usr/bin/env bash
   echo "==== build local llvm ===="
   export BEGINNING_CPP23_SRC_PATH=$HOME/projects/learn/C++/beginning_cpp23
   # clang++ is the locally built clang++ from llvm latest by default
   cmake -G Ninja -S . -B build -DCMAKE_CXX_COMPILER=clang++
   cmake --build build
