= 面向对象

* 多态

```java
public class Test{
    public static void main(String[] args) {
        Father p =  new Son();
        System.out.println(p.getName());//Son  这个可以理解
        System.out.println(p.name);//Father  这是为什么？？

    }

}

class Father {
    public String name = "Father";
    public String getName() {
        return name;
    }
}
class Son extends Father {
    public String name = "Son";
    public String getName() {
        return name;
    }
}
```


多态只适用于方法，对字段不起作用。
另外，写代码的时候，打开编译器警告“Field declaration hides another field or variable”，严禁子类声明与父类重名的变量。

interface的字段只能是public static final类型

* Java编译器最终编译出的.class文件只使用完整类名，因此，在代码中，当编译器遇到一个class名称时：
** 如果是完整类名，就直接根据完整类名查找这个class；
** 如果是简单类名，按下面的顺序依次查找：
*** 查找当前package是否存在这个class；
*** 查找import的包是否包含这个class；
*** 查找java.lang包是否包含这个class。

* 如果按照上面的规则还无法确定类名，则编译报错。
* 编写class的时候，编译器会自动帮我们做两个import动作：
** 默认自动import当前package的其他class；
** 默认自动import java.lang.*。

* 把方法定义为package权限有助于测试，因为测试类和被测试类只要位于同一个package，测试代码就可以访问被测试类的package权限方法。

* 一个.java文件只能包含一个public类，但可以包含多个非public类。如果有public类，文件名必须和public类的名字相同。

* 创建类的原因：
** 对现实世界的对象建模：学生，老师
** 对抽象对象建模：形状，事件，事务
** 隐藏实现细节：XX营销策略
** 创建中心控制点：控制器（controller)
** 让参数传递更顺畅：把持久化对象(persistent object)做成一个类
** 隔离一些特殊的复杂度：工厂模式

* 较旧版本的JDK中，字符串在Java内部是用一个char[]数组来表示的。而新版本中String用byte[]存储
** `String s=new String(new char[]{'H','e','l','l','o'})`

** `UTF-8` 编码的另一个好处是容错能力强。如果传输过程中某些字符出错，不会影响后续字符，因为 `UTF-8`编码依靠高位字节来确定一个字符究竟是几个字节，它经常用做传输过程中的编码。
* 