#+title: 寻找德意志
* 第一章
王二是当代中国的一个大学生，他做着去德国学数学的梦。

说是“当代中国”，多少有些故弄玄虚，因为其实作者所指的是公元 2020 年。这一年，先是澳大利亚山火，加拿大雪灾，巴黎暴乱，还有杀死了全球几百万人的新型冠状病毒肺炎 2019-nCoV 。恍然间有种末日气氛，但王二因种种异象更为兴奋，倒不是王二特立独行，而是因为古往今来的年轻人们都喜欢紧张刺激的本性使然。在这一年里，王二在一个朦胧的早晨收到了第八个女朋友的分手消息。她是一个高挑的女孩，每天的生活是刷朱一龙的微薄，画设计图，和王二聊天。在三月里王二沉浸在椭圆曲线和范畴里，并且每天上午发现了几个椭圆曲线的定理后总是非常困，一睡就睡到傍晚六点半，让女孩觉得自己受了冷落。但王二是在自欺欺人，他知道还可能是自己在 2020 年的第一天和她睡觉，让她摸到了自己的下半身，却没有对她做什么。这件事就像一根刺扎在骄傲的女孩心里。他知道还可能是因为自己在女孩眼里逐渐变得无趣：在三月里他开始跟她谈论泛性质，讨论费马大定理，兴奋的说明自己又发现了一个黎曼猜想的证明，而不是和女孩谈论建筑、俄罗斯文学和语言学。也许这是两个志趣不同的人，分手是早晚的事。但建筑、俄罗斯文学和语言学的确是王二喜欢的；女孩却不喜欢数学。没有几个女人喜欢数学，男人也是，但喜欢数学的男人要比女人多一些。有人告诉我不能这么写，因为会被女权主义者们骂。我不想被骂，所以我加上一句注解：“喜欢数学的男人要比女人多一些”是统计学上的事实，但这本书上的其他内容均出自作者编造，纯属虚构，如有雷同，概不负责。

王二在 2020 年总想着用知识吸引女孩来和他谈恋爱，于是他所吸引来的就是整天和他谈论陀思妥耶夫斯基对天主教的态度、毛姆是个渣男、Julia 语言是人类的希望诸如此类话题的女孩子。但是少男少女在一起并不是为了谈论这些。孤独感驱使他们寻找同类，孤独感的背后却是肉体上的欲望。谈论高尚的知识难以顺利过渡到上床睡觉，这是王二爱情策略的底层缺陷。这就是为何王二谈了八个女票却还是个处男的原因。

王二初学范畴论时，只有周岁三岁。他的父母望子成龙，给他报了英美文学、范畴论、同伦类型论和古典音乐鉴赏的胎教班。也许是胎教班底子打得好，王二在三岁时仍旧对范畴论怀有兴趣。但他那时只是为了好玩，喜欢乱画交换图，只学语法不通语义，丝毫不懂前辈数学大师们发明这套抽象语言是为了什么。直到他 21 岁，还在大学的时候，谈了第八个女朋友，被激发了幼时的兴趣，学习了代数拓扑和代数几何，才懂了当初那些箭头的含义。

说到代数拓扑和代数几何，也许读者诸公都比我更清楚。代数几何似乎已经位居基础数学的中心地位。简言之，代数几何就是要研究多项式的零点，代数拓扑则是用代数工具研究拓扑空间。我们的王二生性大胆，举例来说，他在小学二年级时炸过学校茅坑，五岁时就偷拿家里钱买玩具车。但他在数学学习中可以说是谨小慎微，例如，他为了学习 Basic Topology ，下载了 Munkres 的 Topology ， Atchar 的 Algebraic Topology ， John Conway 的 A course in Point Set Topology ，还去搜集了 Munkres 那本书的 Solutions ，才心满意足开始看书学习拓扑学。他把 John Conway 的那本作为主要教材。每有所得，王二自信爆棚继续读；但只要被卡住，王二就会求助其他书，每每在其他书里看到相关概念，就会沉迷进去忘记自己的主要问题；王二求助 Wikipedia 和 nLab 时也是这个情况。这说明王二在数学的世界里并不感觉自在。这说明王二也许并不是做数学的料。据说 Peter Scholze 在线性代数都没系统学过时就去看 Harris & Taylor 的局部朗兰兹对应的证明。Peter Scholze 读懂那一百页论文之后就懂了里面用到的各种数学，还对证明进行了严格的简化，发明了四大。（四大是什么？）王二在数学上没有这样的勇气。这是王二许多悲剧的开始。

王二在三月沉迷数学世界时，已经隐隐约约意识到自己去德国学习数学只是一个奢望。他每天六点半起床，洗漱完毕，把两小杯黄豆和半杯大米放到九阳破壁机里打豆浆，在六点四十五开始背德语单词，七点二十开始背德语课文，间或学语法。整个早晨奉献给德语。八点开始吃早饭，八点半吃完。吃完就会有些困，王二这时选择睡觉。也许大早上睡觉显得很萎靡，但王二并不在意他人看法。他只睡半小时，九点二十分继续学习。在三月里，他主要学微分几何、椭圆曲线、范畴论和拓扑学。每天的上午他主要学范畴论和椭圆曲线。有时在看数学书时他会想：这一切是梦吧。发生了一场大瘟疫，于是不必呆在又冷又没有朋友的学校里，又有了一个漂亮可爱的女朋友，还可以天天看自己早就想看却一直没有机会看的书，体悟其中的奇妙世界。不过，大部分时间里他都清清楚楚地明白自己身处现实。现实是痛苦和欢乐并存的地方。


