:PROPERTIES:
:ID:       20211105T191439.335939
:END:
#+title: Further Reading
* 说明
这是对Needham新书Visual Differential Geometry and Forms的附录的翻译，又名给未来
几何学家和拓扑学家的阅读建议。
在开始Needham的原文之前，我想引用伍鸿煦先生的他的《黎曼几何初步》里引用过的一
段话，这段话是当代英国演员罗伦士奥利维亚在1947年Old Vic戏剧学院开幕典礼中，向学
生致 辞的一部分。
#+begin_quote
“你们的事业的成长，应该像一棵树的成长一样，应该是顺其自然、无间断和全面的。我希
望你们的根能够在这个学院的肥沃土地下面尽量深入，以使你们的树干长得既粗且壮。这样，
将来无论树叶多么茂盛丰满，也永不会有水分供应不暇的毛病。在上空将不时会有狂风大雨，
也会有行雷闪电。所以切勿长得太快太高。
#+end_quote
以下为原文。

* 前言
下面，我仅仅列出标题和作者；全部细节可以在文献目录里找到[fn:1]。某些作品被列进
来仅仅因为他们与主题高度相关，而我相信他们值得引起你的注意（即使他们并不是我的
菜）。然而大多数作品被列进来是因为我认为他们如珍宝一般，而我向你强烈推荐它们。许
多其他极好的书躺在我的书架上，我也经常寻求他们的建议，然而他们并没有被包括进来，
仅仅因为我努力把这个（已经很长的）书单削减到可管理的长度----我向这些伟大作品的作
者感到道歉。最后，我也对我还没有发现的伟大作品的作者先说一句抱歉！
* 整体推荐
首先，让我用我认为非常有价值的六部作品来做铺垫，每部作品的内容都是 涵盖了本书的
多个章节。
** The Road to Reality, by Roger Penrose （罗杰。彭罗斯）.
  一部几乎涵盖所有物理学和大部分数学的非凡全景图，由这两个领域的大师撰写。许多见
  解只有在这里才能找到，而且这些见解被彭罗斯出色的（和美丽的！）手绘赋予了生命。
** Gravitation, by Misner, Thorne, and Wheeler.
  在1973年首次出版后的近50年里，这部经典之作仍然是对爱因斯坦的几何引力理
  论（广义相对论）和它所依据的微分几何的最好介绍之一。它也包含了对微分形式的最好
  的、最具几何性的介绍之一，包括允许人们有效计算黎曼张量的曲率2-forms。普林斯顿
  大学出版社的新版（2017年）做得很好，并包含了Charles Misner和Kip Thorne的新介绍，
  讨论了自该书出版以来该领域令人兴奋的发展。
** Differential Geometry in the Large, by Heinz Hopf.
  Hopf不仅是二十世纪数学界的杰出人物之一，也是一位论述的大师。在这里，微分几何
  学和拓扑学的思想（其中许多是由Hopf本人提出的）以一种美丽的方式汇集在一起，以
  非凡的清晰度和简单性进行解释。每当我再次阅读这本《大师作品》，我就觉得有位仁慈的魔
  术师在书中插入了更多美妙的想法，因为我发誓，在我上次看的时候，这个美丽的想法还
  没有出现在书页上！"。
** Elementary Differential Geometry (revised 2nd edition), by Barrett O’Neill.
  这本开拓性的书于1966年首次出版，开创了在本科阶段使用微分形式的先河。半个多世纪后的
  今天，在我看来，O'Neill的作品仍然是本科阶段对这一主题唯一最清晰、最优雅、最（讽
  刺吧？）现代的处理方式（除了当代的同类书籍！）。
** Geometrical Methods of Mathematical Physics, by Bernard Schutz.
  这部作品（现在已经有40年的历史了！）是一个永恒的宝库，涵盖了流形、张量、李导数
  和李群、形式、黎曼几何、规整理论以及其他大量的物理学应用。为了实现这一目标，
  Schutz教授成为了《星际迷航》中的斯波克先生。他的另一半瓦肯人格使他能够建立一个完美的晶
  体逻辑结构，其中每一件事都被简明而严格地证明，而且--与我在本书中的（我希望是美
  味的）芝士汉堡方法不同--犹太教规被严格遵守：依赖于公制存在的概念被严格而明确地
  与那些不依赖于公制的概念分开。但是，与此同步，Schutz能够利用他的另一半人格来提供
  丰富的直觉，揭示出潜在的几何现实。
** Mathematics and Its History (3rd edition), by John Stillwell.
  通过历史的视角，对所有的数学进行了一次出色的全景展示。但不要误解，这主要不是一
  本关于历史的书，相反，它从根本上是一本关于数学本身的相互联系和意义的作品，所有
  这些都以一种相当简洁的风格（相对于我来说！）来解释，具有深刻的洞察力和清晰的思路。

* 一般几何学推荐
以下作品涉及一般的几何学，尤其是双曲几何学。(微分几何学有它自己的类别）。
** meGeometry and the Imagination, by David Hilbert and S. Cohn-Vossen.
  这是20世纪最伟大的数学家之一对几何学进行的一次宏伟而深刻的调查，重点在于直观的
  理解。这些图表（由K.H.Naumann和H.Bödeker绘制）具有令人惊叹的美，令我羡慕不已。
** Experiencing Geometry, by David W. Henderson and Daina Taimina.
  一个非常不寻常的方法，在哲学上类似于我的方法（但使用Moore方法），专注于几何学
  的直观、实验性调查。它包含对平行移动和整体性的重要讨论。他们的方法与我的方法的
  重叠在序言中的这段引文中得到了明确。"本书是基于这样一种观点：证明是一种令人信
  服的交流，它回答了为什么？（重点在斜体字）。（原文引号中为“This book is based on
  a view of proof as a convincing communication that answers—Why?”，其中a
  convincing communication that answers--Why? 为斜体。）
** Introduction to Geometry (2nd edition), by H.S.M. Coxeter.
  精彩清晰的评述，出自一位当代大师之手。
** Geometry, by Brannan, Esplen, and Gray.
  一本优秀的现代几何学概览，基于克莱因对变换群的看法。
** Euclidean and Non-Euclidean Geometries: Development and History, by Marvin J. Greenberg.
  这是一部有价值的、详细的双曲几何学发展史，包括对Gauss、Bolyai和其他许多人的关键性私人信件的长篇引用。
** The Poincaré Half-Plane, by Saul Stahl.
  标题说明了一切。
** Geometry Revealed, by Marcel Berger.
  高级得多的几何学评述，出自20世纪最伟大的几何学家之一，重点是概念性的证明和未解
  决的问题。

* 拓扑学
** Intuitive Topology, by V. V. Prasolov.
  不到100页的篇幅，而且充满了图表，这本超级友好的入门书不愧于它的标题!
** Euler’s Gem, by David S. Richeson.
  对欧拉的多面体公式的历史和相关的数学思想进行了精湛的、数学上准确而又引人入胜的描述。
** Surface Topology, by P. A. Firby and C. F. Gardiner.
一本非常友好、图文并茂的介绍拓扑学的基本 *几何* 思想的书。
** First Concepts of Topology, by W. G. Chinn and N. E. Steenrod.
另一本非常友好、图文并茂的介绍拓扑学的基本 *几何* 思想的书。

* 翻译说明
- 文中的“形式”原文为Forms，应该理解为微分形式。

* Footnotes

[fn:1] 见作者的书Visual Differential Geometry and Forms中的参考文献目录。
