:PROPERTIES:
:ID:       20211119T000249.712106
:END:
#+title: math advice
1. read =word power made easy= and Li PingWu
2. Use your English skills! Go to Math StackExchange and MathOverflow.
3. Learn Mathmetical Analysis and Linear Algebra. Recommend books include Zhang Zhusheng, zorich, Taorence Tao, Linear Algebra Done Right.

4. 背单词不外乎要靠一点技巧和坚持。我常用的技巧一是根据读音来记忆单词，学习音标和发音规律，做到看到一个单词能差不多把读音读对，然后反过来能差不多根据读音正确拼写单词。二是根据词根词缀记忆。英语常用的词缀也就几百个，掌握这些词缀等于掌握成千上万个单词。推荐读李平武的《英语词根与单词的说文解字》和《英语词缀与英语派生词》。前者应该是国内最早系统讲解词根的书，我觉得写得非常好，好好读下去并记忆，英语单词一定大涨。另外国外有本word power made easy，分话题地根据词根记忆单词，可以当作记忆词汇的课本来看，内容非常好。国内有翻译版叫《英语说文解字》。
5. 另外背诵记忆英语单词不是目的，若是只背不用，不仅枯燥无味还容易忘。既然你可以坚持背下来单词，又想学数学，那就去Math StackExchange或者MathOverflow跟国际友人交流数学问题吧。这两个网站上质量很高，上面禁止跟数学主题无关的话题，在这上面问数学问题比在知乎上问效率高多了。reddit上的数学版块和 artofproblemsovling也可以看看，后者是研究数学竞赛的。

6. 至于*真正*提高数学水平，没有什么捷径，去学就行了。至于怎么学，先学什么后学什么，可以看看国外很多优秀大学数学系的教学大纲，或者中科大前辈编写的ustcmathplan3（我回答过，可以在知乎上搜到）。数学分析和高等代数一定要学好，学习这两门课时可以学习一下数理逻辑，我觉得这门课对数学入门者练习写证明和熟悉数学的语言非常有好处。选教材你应该懂，国内的教材好的不多，选之前可以看看豆瓣知乎评价。国内的数学分析教材推荐张筑生，高等代数教材推荐丘维声或者蓝以中，数理逻辑推荐复旦的《数理逻辑：证明及其限度》，今年这本书出了第二版。国外的好教材就浩如烟海了，哪个领域的书你去谷歌一搜就看到了（翻墙肯定不是问题吧）。

7. 我今年暑假教一个初中小女孩数学，教她学高一数学知识，她学得很快而且课后题都能做出来。两周多她就快把高一学完了。我觉得高中知识真的不难，推荐你初三暑假找个靠谱的老师带着把高中数学一个初三暑假（差不多三个月呢）学完（课后题目都要做出来，不做出来等于学个半吊子，还不如不学）。然后你高中可以就可以悠闲一些学数学分析高等代数和数理逻辑，同时搞数学竞赛。大学数学内容用于提高眼界和学下去的动力，因为数学你越学进去就会觉得越美，而高中单薄的圆锥曲线立体几何什么的只会消磨人学习数学的动力。据我说之数学竞赛也是技巧居多，并不能带人欣赏数学的美，所以学“高等”一些的数学保持对数学的激情还是很重要的。
   我大学没有清北好，我也不是数竞党，以上仅供参考。
