:PROPERTIES:
:ID:       20211105T191439.335939
:END:
#+title: Further Reading
aka. 给未来几何学家和拓扑学家的阅读建议

在开始Needham的原文之前，我想引用伍鸿煦先生的他的《黎曼几何初步》里引用过的一
段话，这段话是当代英国演员罗伦士奥利维亚在1947年Old Vic戏剧学院开幕典礼中，向学
生致辞的一部分。
#+begin_quote
“你们的事业的成长，应该像一棵树的成长一样，应该是顺其自然、无间断和全面的。我希
望你们的根能够在这个学院的肥沃土地下面尽量深入，以使你们的树干长得既粗且壮。这样，
将来无论树叶多么茂盛丰满，也永不会有水分供应不暇的毛病。在上空将不时会有狂风大雨，
也会有行雷闪电。所以切勿长得太快太高。
#+end_quote
下面是Needham的新书Visual Differential Geometry and Forms的附录：Further Reading
的翻译。翻译这个附录是因为我觉得这个附录是给未来几何学家和拓扑学家极好的阅读建议。

Notes: 下面，我仅仅列出标题和作者；全部细节可以在文献目录里找到。某些作品被列进
来仅仅因为他们与主题高度相关，而我相信他们值得引起你的注意（即使他们并不是我的
菜）。然而大多数作品被列进来是因为我认为他们如珍宝一般，而我向你强烈推荐它们。许
多其他极好的书躺在我的书架上，我也经常寻求他们的建议，然而他们并没有被包括进来，
仅仅因为我努力把这个（已经很长的）书单削减到可管理的长度----我向这些伟大作品的作
者感到道歉。最后，我也对我还没有发现的伟大作品的作者先说一句抱歉！
* 整体推荐
首先，让我用我认为非常有价值的六部作品来做铺垫，每部作品的内容都是 涵盖了本书的
多个章节。
- The Road to Reality, by Roger Penrose （罗杰。彭罗斯）.
  一部几乎涵盖所有物理学和大部分数学的非凡全景图，由这两个领域的大师撰写。许多见
  解只有在这里才能找到，而且这些见解被彭罗斯出色的（和美丽的！）手绘赋予了生命。
- Gravitation, by Misner, Thorne, and Wheeler.
  在1973年首次出版后的近50年里，这部经典之作仍然是对爱因斯坦的几何引力理
  论（广义相对论）和它所依据的微分几何的最好介绍之一。它也包含了对微分形式的最好
  的、最具几何性的介绍之一，包括允许人们有效计算黎曼张量的曲率2-forms。普林斯顿
  大学出版社的新版（2017年）做得很好，并包含了Charles Misner和Kip Thorne的新介绍，
  讨论了自该书出版以来该领域令人兴奋的发展。
- Differential Geometry in the Large, by Heinz Hopf.
