
* 2020
** 2020-06 六月
*** 2020-06-10 星期三
**** [2020-06-10 三 04:56]
我是个没有恒心的人吗？
公无渡河，公竞渡河，渡河而死，其奈公何！

***** DONE 如何同步 pyim 的词库
1. 去看 pyim 的 github 仓库
2. 把本地 pyim 词库同步到 github
3. 把本地 pyim 词库同步给 fcitx5
不需要同步了。问题变成如何同步 emacs-rime 的词库。
*** 2020-06-11 星期四
**** [2020-06-11 四 16:39]
今天做了一个艰难的决定。
研究生（准确来说是硕士）阶段不出国了，博士阶段再出国。
研究生考中山大学的基础数学。为了 Annie，也因为中山大学的基础数学的确不错。其实我更想考中科大的基础数学的。
*** 2020-06-12 星期五
**** [2020-06-12 五 15:32]
今天可以放下一切北京交通大学的东西了，哦不，还有数理统计学，一门专业限选课和毕业设计。话说这三件事也挺烦人的。

可以 __安心__ 准备考研计划了。
**** [2020-06-12 五 19:29]
使用 org-capture 时自动链接到当前 buffer 这个特性属实烦人。如何解决？
[[TODO 修正使用org-capture时自动链接到当前buffer这个特性]]
哇，原来这就是使用 org-mode 链接到某文件的某一 headline 的示例，爱了爱了。 #tip
[[file:~/projects/learn/Notebook/org/journal.org::*\[2020-06-12 五 15:32\]]
*** 2020-06-13 星期六
**** [2020-06-13 六 05:31]
今天继续思考出路。加上 Annie 今天考试，我却很紧张，睡不着。
仔细反思了这几天的作为。太颓废了。
***** 荒野乱斗这个游戏也没什么意思嘛，我却在上面浪费了太多时间。
所以我把它卸载了。
以后想玩游戏的时候，我就可以提醒自己学数学，而我当然会甘之若饴，想想就很开心啊。
***** 没有好好规划时间
那就好好去规划。
***** 丧失激情和渴望了吗
没有。
**** [2020-06-13 六 07:08]

***** TODO org-agenda 该怎么用？
***** WAIT pyim 太慢了，如何优化？
使用 emacs-rime 代替 pyim ，效果很不错。
***** WAIT 尝试使用 emacs-rime 替代 pyim 以提升速度
*** 2020-06-14 星期日
**** [2020-06-14 日 00:20]
真是一个奇怪的特性啊。
#+BEGIN_SRC elisp
setq-default preview-document-pt x

#+END_SRC
中 x 是一个数值，但是值越大，preview 时图片就越小。
When x === 5 the effect is best (tested).

[[file:~/projects/learn/Notebook/try_latex.tex::TeX-PDF-mode t)(setq-default TeX-engine 'xetex]]
**** [2020-06-14 日 19:39]
慕强的人注定走向庸俗吗？

**** [2020-06-14 日 23:23]
良好的表述和沟通在数学上如同在人文科学中一样重要。
*** 2020-06-15 星期一
**** [2020-06-15 一 23:31]
今天的 linux 知识：
#+BEGIN_SRC shell
ln -sf <dir1> <dir2>

#+END_SRC
这样的命令，当 dir2 已经存在时，会在 dir2 中创建一个软链接，指向 dir1 ；当 dir2 不存在时，会创建名为 dir2 的软链接，指向 dir1 。
**** [2020-06-15 一 20:47]
一个高中同学更新了朋友圈和 QQ 空间动态，是自己的书桌和书柜。看到有两本书是我高中时借给过他的：《宇宙的琴弦》和南伊利诺伊思大学的《微积分》翻译版第九版。想起了我跟他做同桌的时光。原来我也可以影响别人啊。

**** [2020-06-15 一 10:50]
manateelazycat 的 emacs 学习经验分享：
#+BEGIN_QUOTE
学习 Emacs 有几条曲线:

    先会用基本的快捷键, 安装各种简单的插件, 抄各种各样的配置, 先体验一下 Emacs 的强大功能.

    安装复杂插件, 被各种配置搞崩溃了, 越改挂的越厉害, 大部分人卡在这个阶段, 因为不会 Elisp, 导致东拼西凑的方法对于复杂插件行不通

    你搞不懂 Emacs 复杂的配置的原因是因为你不懂 Elisp 编程, 学习 Elisp 的方法: 老老实实读 Emacs 内置的 Elisp reference manual, 这么厚的手册怎么学?

    一页一页的挨着看, 一个 API 一个 API 的读, 不要跳过
    每个 API, 都在 ielm 里面实践一下
    遇到不知道啥鬼用的 API, 去 Google 或 EmacsWiki 上搜索一下, 看看别人怎么用这些 API 的?

    如果你花了一个月耐下心读完 Elisp reference manual 以后, Emacs 90% 以上的代码你都可以看懂了, 继续折腾复杂插件, 知道 require, autoload, set-key, 各种 hook, defadvice 的在不同环境下的细微差别, 编程上知道 save-excursion, ignore-errors 这些风骚 macro 的用法. 这个阶段可以尝试手动来写一写复杂的配置了, 这个阶段你已经是 Emacs 高级用户了.

    如果还不满足, 可以像我这样造点有趣的轮子: My Emacs Plugins 34 , 如果你自己会写 Elisp 插件, 你会发现 Emacs 其实是越用越简单的, 因为包括正则表达式, 语法高亮, 模式, 异步子进程, hook, overlay, advice 这些代码你写熟悉以后, 你会发现所有插件的唯一差别就是复杂度和想象力的区别, 不存在想得出来写不出来的东西.

    到了这个阶段, 唯一可以让你学习到更多知识的就是去 IRC #emacs 和那些古老的黑客们交流, 或者去扒 Github Emacser, 我知道很多日本牛逼哄哄的 Emacs 开发者都把插件放到 ftp 上 (比如当年的 color-moccur.el ), 学点 Google 语法就可以定向搜索. 这些人都是你会写 Emacs 插件后, 需要学习和进阶的榜样, 这时候你再看 Elisp 代码, 你的注意力会放在他们 Elisp 编程的一些细节上, 比如代码写的更简洁, 方法用的妙, 架构设计上等等, 这是完全不同阶段的探索体验.

    如果你还不满足, 好好学习 C 语言, 然后再找个赚钱的工作, 把自己和家人照顾好. 业余时间直接用 C 或 Elisp 给 Emacs 底层做贡献, 把你的代码贡献固化到 Emacs 中, 然后你的名字可以像我一样写到 Emacs AUTHORS 里面去装逼: Emacs AUTHORS 92

如果你已经看到这里, 而且也做到上面的所有 7 点, 你自己的能力和精神境界都会很高了, 再也不会咋咋呼呼的吵着自己的技术要咋样咋样, 因为你会发现学的越多, 自己就是傻逼一个, 啥都不懂, 这辈子即使终身学习也学习不完, 哈哈哈哈.

上面就是我学习 Emacs 十多年的经验分享, 希望可以给同学们一点参考.
#+END_QUOTE

[[file:~/projects/learn/Notebook/org/journal.org::*\[2020-06-15 一 10:03\]][[2020-06-15 一 10:03]​]]
**** [2020-06-15 一 10:03]
有一次，希尔伯特对哈拉德 波尔(Harald Bohr) 说道：“我之所以能够取得一些数学成就，实在是因为我觉得数学是如此之难。我在阅读或在谈论数学的时候，总觉得它太难，几乎无法理解它；于是，我情不自禁地想，它不能变得简单些吗？结果呢，”，希尔伯特脸上露出孩子般的笑容，继续说道，“有几次，我终于发现它确实比较简单！”
**** [2020-06-15 一 09:26]
emacs-rime 用起来不错啊，即使没有跟随式的候选框。因为大部分时间不需要候选框，需要时再去看 minibuffer 也不错，可以降低干扰。
*** 2020-06-16 星期二
**** [2020-06-16 二 04:27]
***** TODO 需要给源代码作者报告 iced 的 counter 例子在 wayland 下便宜失败
***** TODO For me the only XWayland apps that I want to use on the HiDPI display are Chromium and VSCode and both of them have options for scaling (e.g.: "--force-device-scale-factor=2" for Chromium; "window.zoomLevel" for VSCode). 
