:PROPERTIES:
:ID:       ab1ebce2-8a7c-42b3-955e-eb9bae7d0eb1
:END:
#+title: 《傲慢与偏见》
*  读后感
时隔7年，写一个对这本书的读后感。

这本书讲述英国乡下贵族的女儿伊丽莎白和富有的单身汉达西的爱情故事。他们从初见就产生误会，伊丽莎白对达西抱有偏见，之后的一些事更是让误会逐渐加深，但日久见人心，坑蒙拐骗的伪君子终于被揭露，温柔美丽、幽默风趣的伊丽莎白和慷慨大方的达西终于消弥误解、走到一起。在这一对情人之外，简 奥斯汀还描绘了丰富的英国19世纪处的乡村社会风情，反映出19世纪英国乡绅阶层的礼节、成长、教育、道德、婚姻的情态。
  书中描绘了这么多婚姻的故事，引导我思考，婚姻究竟是什么？从社会的角度看，婚姻是两个人建立家庭的保证，婚姻是爱情的结果。所以更好的问题是，爱情究竟是什么？或者说，完美的爱情应该是什么样的？我们为什么需要爱情，人们为什么总是耗费这么多精力去追求爱情呢？为什么要为爱情寻寻觅觅，痴狂半生呢？
  女主角的父母--贝内特夫妇婚姻和爱情绝对称不上幸福的、完美的。贝内特先生喜好读书，性格沉静，理性，喜欢幽默和反讽，而贝内特太太爱八卦，“智力平庸、见识短浅、喜怒无常”。两人完全没有共同语言的性格，当然不会有共同的精神追求，当然不会有温柔的感情慰藉，于是当然不会有炽热的爱情，那婚姻当然也就沉闷无味。
  丽迪亚和威克姆之间算做爱情吗？不过是花花公子哄骗涉世未深的小女孩的寻常故事。当小女孩看到自己心中的王子不过是一个坑蒙拐骗之徒，当花花公子转向下一个行骗目标，激情褪去，友情都不能维持了，遑论爱情。
  女主角伊丽莎白和男主角达西之间的感情呢？他们曾有误会，但误会之雾吹散后，信任的大树更加茁壮。他们有相同的志趣、共同的话题，伊丽莎白有良好的教养、姣好的面容，达西则有着严谨高傲却又慷慨大方的性格，优渥的家产，谁能不说他们是完美一对呢？
  那么，我可以总结出完美的爱情应该是什么样的了：
  1. 信任和真诚。双方都真诚相待，没有勾心斗角、尔虞我诈。应该给予所爱之人无条件的信任，如果对爱的人还处处提防，那为什么要爱这个人呢？反过来，如果一个爱你的人不信任你，那这称得上爱吗？丽迪亚和威克姆建立在谎言之上的爱情，当谎言破碎，爱情自会消散。
  2. 共同的精神追求。好的爱情里，双方应该有共通的人生观、价值观。不可能要求一个充满激情的共产者和一个想叱诧市场的资本家之间产生爱情吧？
  3. 对于彼此的情感抚慰、情绪价值。毕竟爱情的另一个名字叫做“亲密关系”啊。爱人应该是自己在这世界上最温暖的港湾。
  4. 可以促进彼此成长为更好的自己。如果和一个人在一起要压抑了自己的天性，扮作另外的人，去做自己不喜欢的事，那一定不是真正的爱情。
  5. 肉体的满足。
  我觉得这五点是完美爱情必备的五个条件。我以后将以此作为追求爱情的标准。
